In [1]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.4.0


In [2]:
arr = np.array([[1, 2], [3, 4]])

In [3]:
x = tf.constant(arr)

In [4]:
x.ndim

2

In [5]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [6]:
x.dtype

tf.int32

In [7]:
x.numpy()

array([[1, 2],
       [3, 4]])

In [8]:
x[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4])>

In [9]:
y = tf.constant([[5, 6], [7, 8]])

In [10]:
y.numpy()

array([[5, 6],
       [7, 8]])

In [11]:
z = x + y
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [12]:
z = tf.add(x, y)
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [13]:
zm = x*y
zm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [14]:
zm = tf.multiply(x, y)
zm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [15]:
tf.matmul(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [16]:
x.numpy()[0,0] = 500

In [17]:
x.numpy()

array([[1, 2],
       [3, 4]])

In [18]:
v = tf.Variable(arr)
v

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [19]:
v.numpy()[0, 0] = 500
v.numpy()

array([[1, 2],
       [3, 4]])

In [20]:
v.name

'Variable:0'

In [21]:
tf.multiply(v, v)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]])>

In [22]:
v.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [23]:
x = tf.constant(3.0)
z = tf.constant(2.0)
with tf.GradientTape() as tape:
    with tf.GradientTape() as tape2:
        tape.watch(x)
        tape2.watch(z)
        y = x*x*z**2
        dy_dx = tape.gradient(y, x)
        dy_dz = tape2.gradient(y, z)
        print(dy_dx.numpy())
        print(dy_dz.numpy())
    

24.0
36.0


In [41]:
n_samp, n_dim = v.numpy().shape
v_arr = v.numpy()

In [42]:
v_b = np.ones((n_samp, n_dim+1))
v_b[:, 1::] = v_arr
v_b

array([[1., 1., 2.],
       [1., 3., 4.]])

In [43]:
tf.convert_to_tensor(v_b)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 2.],
       [1., 3., 4.]])>

In [51]:
arr = np.arange(0, 16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
arr[16]

IndexError: index 16 is out of bounds for axis 0 with size 16

In [55]:
act_list = [tf.nn.relu, tf.math.sigmoid, tf.identity]

In [59]:
act_list[0](-25)

<tf.Tensor: shape=(), dtype=int32, numpy=0>