In [3]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.4.0


In [4]:
arr = np.array([[1, 2], [3, 4]])

In [5]:
x = tf.constant(arr)

In [9]:
x.ndim

2

In [10]:
type(x)

tensorflow.python.framework.ops.EagerTensor

In [11]:
x.dtype

tf.int32

In [12]:
x.numpy()

array([[1, 2],
       [3, 4]])

In [18]:
x[:,1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4])>

In [20]:
y = tf.constant([[5, 6], [7, 8]])

In [21]:
y.numpy()

array([[5, 6],
       [7, 8]])

In [26]:
z = x + y
z

Wall time: 0 ns


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [24]:
z = tf.add(x, y)
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [27]:
zm = x*y
zm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [28]:
zm = tf.multiply(x, y)
zm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [29]:
tf.matmul(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [33]:
x.numpy()[0,0] = 500

In [31]:
x.numpy()

array([[1, 2],
       [3, 4]])

In [35]:
v = tf.Variable(arr)
v

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [37]:
v.numpy()[0, 0] = 500
v.numpy()

array([[1, 2],
       [3, 4]])

In [38]:
v.name

'Variable:0'

In [44]:
tf.multiply(v, v)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]])>

In [45]:
v.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [20]:
x = tf.constant(3.0)
z = tf.constant(2.0)
with tf.GradientTape() as tape:
    with tf.GradientTape() as tape2:
        tape.watch(x)
        tape2.watch(z)
        y = x*x*z**2
        dy_dx = tape.gradient(y, x)
        dy_dz = tape2.gradient(y, z)
        print(dy_dx.numpy())
        print(dy_dz.numpy())
    

24.0
36.0
